### ISSUE TITLE
失效了！但是BAE你部署的示例还好用

### ISSUE THREAD

**Issue by fhmob** [daimajia/bleed-baidu-white#10]
失效了，看了一下代码，md5还能提取到，B.dlink+"&response-cache-control=private"+_:B.dlink+_; 这个地方出问题了，本地测试的时候：
{
  "error": true, 
  "id": "1938327270", 
  "type": "baidu", 
  "uk": "2855000475", 
  "url": "http://pan.baidu.com/share/link?shareid=1938327270&uk=2855000475"
}

**Comment by daimajia** [comment]
由于每次开源失效被打压，现在已经很无奈的不push最新代码啦，都在我部署的环境里，你可以直接用这个服务哇！
Sent using CloudMagic 
On 周三, 5月 07, 2014 at 10:38 下午, fhmob notifications@github.com wrote:失效了，看了一下代码，md5还能提取到，B.dlink+"&response-cache-control=private"+:B.dlink+; 这个地方出问题了，本地测试的时候：
{
  "error": true, 
  "id": "1938327270", 
  "type": "baidu", 
  "uk": "2855000475", 
  "url": "http://pan.baidu.com/share/link?shareid=1938327270&uk=2855000475"
}
