### ISSUE TITLE
为什么更新仓库了

### ISSUE THREAD

**Issue by NanguangChou** [daimajia/bleed-baidu-white#12]
看了index.py才发现是一年前的，能开源吗:)

**Comment by daimajia** [comment]
不能开源了 每次开源很快就会失效 实属无奈之举。现在请放心用服务吧。On 周一, 8月 11, 2014 at 16:53,  daimajia/bleed-baidu-white reply@reply.github.com wrote:            看了index.py才发现是一年前的，能开源吗:)

**Comment by NanguangChou** [comment]
百度的问题?

**Comment by daimajia** [comment]
说不准On 周一, 8月 11, 2014 at 16:56,  daimajia/bleed-baidu-white reply@reply.github.com wrote:            百度的问题?

**Comment by NanguangChou** [comment]
是不是开源了他家公司就封链接

**Comment by daimajia** [comment]
有可能On 周一, 8月 11, 2014 at 16:57,  daimajia/bleed-baidu-white reply@reply.github.com wrote:            是不是开源了他家公司就封链接

**Comment by NanguangChou** [comment]
我就问一问，能不能让我看看上个版本的py代码。。

**Comment by daimajia** [comment]
oh, 可能不行，现在代码一律不放出哦。
