### ISSUE TITLE
解析到的下载链接会过期

### ISSUE THREAD

**Issue by liaol** [daimajia/bleed-baidu-white#16]
例如这个：http://d.pcs.baidu.com/file/863359635889bbec5c937d238734d46e?fid=1448089351-250528-643734050612953&time=1414054798&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-przXcLIaDFx%2FHKuRGQiKxm%2Bx%2BWo%3D&rt=sh&expires=8h&r=831053169&sharesign=OaCp8xTs9S5YsiEZYKJTmOtZwX4rnKbSxFRjJnmbZ0HM60ufxisk/rdM+7QjI9i/9CbTZlGt3BdDEnLpt/A7Jn9pyt5bEPff&sh=1&qq-pf-to=pcqq.c2c
{
    "error_code": 31064,
    "error_msg": "expire time out error",
    "request_id": 3771348710
}

这是百度的限制吗？
有什么解决办法？
谢谢！

**Comment by daimajia** [comment]
过期的事情没办法

**Comment by liaol** [comment]
ok
thanks
