### ISSUE TITLE
不是所有的分享都可以提取出来

### ISSUE THREAD

**Issue by dingyaguang117** [daimajia/bleed-baidu-white#2]
比如：
http://pan.baidu.com/share/link?shareid=3594691956&uk=3107077322

**Comment by daimajia** [comment]
这个好像可以的呐 

http://daimajia.duapp.com/baidu/3594691956/3107077322

**Comment by dingyaguang117** [comment]
咦  刚才不行 难道是我拼错了

**Comment by daimajia** [comment]
一定是你粗心大意了~ 不过很欢迎提意见~
