### ISSUE TITLE
百度分享地址格式变化导致无法使用

### ISSUE THREAD

**Issue by lijinma** [daimajia/bleed-baidu-white#4]
代码家：

（1）[http://daimajia.duapp.com/baidu/445495/2150962024 ](http://daimajia.duapp.com/baidu/445495/2150962024) 无法访问了。

``` json
{
  "url": "http://pan.baidu.com/share/link?shareid=445495&uk=2150962024", 
  "type": "baidu", 
  "id": "445495", 
  "uk": "2150962024", 
  "error": true
}
```

现在百度的分享链接是：

[http://pan.baidu.com/s/1ePGUs](http://pan.baidu.com/s/1ePGUs)，没有shareid和uk了，

有思路再榨一次吗？ hw

**Comment by kerneltravel** [comment]
有，github 里面有个其他项目已经解决这个问题了。链接我回头发上来

On Mon, Nov 18, 2013 at 1:13 PM, 金马 notifications@github.com wrote:

> 代码家：
> 
> （1）http://daimajia.duapp.com/baidu/445495/2150962024 无法访问了。
> 
> {
>   "url": "http://pan.baidu.com/share/link?shareid=445495&uk=2150962024",
>   "type": "baidu",
>   "id": "445495",
>   "uk": "2150962024",
>   "error": true}
> 
> 现在百度的分享链接是：
> 
> http://pan.baidu.com/s/1ePGUs，没有shareid和uk了，
> 
> 有思路再榨一次吗？ hw
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/daimajia/bleed-baidu-white/issues/4
> .

## 

From
kjpioo lyn

**Comment by lijinma** [comment]
@kerneltravel  求提供。。多谢

**Comment by kerneltravel** [comment]
https://github.com/kerneltravel/baiduyun
就是这个地址

On Mon, Nov 18, 2013 at 5:56 PM, 金马 notifications@github.com wrote:

> @kerneltravel https://github.com/kerneltravel 求提供。。多谢
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/daimajia/bleed-baidu-white/issues/4#issuecomment-28685884
> .

## 

From
kjpioo lyn

**Comment by lijinma** [comment]
多谢哈~~ i  gonna try

**Comment by lijinma** [comment]
@kerneltravel  [http://file.icycat.com/baidumini.php?id=1j9EBP](http://file.icycat.com/baidumini.php?id=1j9EBP) 不work啊

我换了好多分享的id，错误都是：分享的文件已经被取消或不存在!

没时间debug，麻烦你看下

**Comment by daimajia** [comment]
@lijinma  @kerneltravel  已经可以支持百度最新变化了，欢迎测试

http://daimajia.duapp.com/baidu/?url=http://pan.baidu.com/s/17Wq4K

**Comment by lijinma** [comment]
@daimajia  多谢 hw~~~

**Comment by daimajia** [comment]
@lijinma 不过这次没开源，因为一开源估计就会被百度K掉。

**Comment by lijinma** [comment]
@daimajia  历史证明，开源肯定要被k掉的，先凑合用吧。哈哈。我现在用七牛，感觉很快，一个月免费10g流量也够了，hw。

**Comment by daimajia** [comment]
@lijinma 蛮爽的~  我也去试试~

**Comment by lijinma** [comment]
@daimajia 通过这个链接[http://portal.qiniu.com/signup?code=3llfwhiykq3wx](http://portal.qiniu.com/signup?code=3llfwhiykq3wx)注册，我能获得5G..哈哈哈

**Comment by daimajia** [comment]
@lijinma 感谢你的邀请链接~
