### ISSUE TITLE
可以做个百度网盘上传脚本吗?

### ISSUE THREAD

**Issue by phoenixg** [daimajia/bleed-baidu-white#5]

**Comment by daimajia** [comment]
这个暂时还没有计划～ 后面可能会增加这个功能。因为验证码问题可能比较难处理。

**Comment by kerneltravel** [comment]
《Linux VPS使用百度网盘API上传备份文件》 http://www.haiyun.me/archives/859.html

用这种方式，直接一个命令 就可以上传文件到 pcs了。

curl -k -L -F "file=@haiyun.me.tar.gz"
"https://c.pcs.baidu.com/rest/2.0/pcs/file?method=upload&\access_token=<access_token>&path=/apps/pcsupload/haiyun.me.tar.gz"

On Tue, Dec 24, 2013 at 9:09 AM, 代码家 notifications@github.com wrote:

> 这个暂时还没有计划～ 后面可能会增加这个功能。因为验证码问题可能比较难处理。
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/daimajia/bleed-baidu-white/issues/5#issuecomment-31153303
> .

## 

From
kjpioo lyn

**Comment by kerneltravel** [comment]
https://github.com/emptyhua/baidu_pcs_cli

2013/12/24 kjpioo kjpioo2006@gmail.com

> 《Linux VPS使用百度网盘API上传备份文件》 http://www.haiyun.me/archives/859.html
> 
> 用这种方式，直接一个命令 就可以上传文件到 pcs了。
> 
> curl -k -L -F "file=@haiyun.me.tar.gz" "https://c.pcs.baidu.com/rest/2.0/pcs/file?method=upload&\access_token=<access_token>&path=/apps/pcsupload/haiyun.me.tar.gz"
> 
> On Tue, Dec 24, 2013 at 9:09 AM, 代码家 notifications@github.com wrote:
> 
> > 这个暂时还没有计划～ 后面可能会增加这个功能。因为验证码问题可能比较难处理。
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/daimajia/bleed-baidu-white/issues/5#issuecomment-31153303
> > .
> 
> ## 
> 
> From
> kjpioo lyn

## 

From
kjpioo lyn
