### ISSUE TITLE
是否能再次开源0.0

### ISSUE THREAD

**Issue by arition** [daimajia/bleed-baidu-white#6]
http://daimajia.duapp.com/ 这个找了一圈好像是现在唯一的免验证码的连接提取了orz
但是没有开源实在很残念啊……我有个c#的项目需要用百度盘的连接提取，每次让用户输验证码毕竟不方便
用http://daimajia.duapp.com/ 来解析也是可以，但是这不支持带密码的分享的解析TAT，而我这边需要解析的大多都是带密码的文件，所以还是希望能够提供一下代码o(_^▽^_)o

**Comment by daimajia** [comment]
这次会发源代码~ 楼主接好~

**Comment by arition** [comment]
@daimajia 你是会push上来还是？

**Comment by daimajia** [comment]
不太可能会push上去了，因为每次push都会很快失效，所以...大家最好直接调用接口，然后我来维护。
2014-1-23 上午12:08于 "arition" notifications@github.com写道：

**Comment by arition** [comment]
@daimajia 所以……你是把带密码解析加上去还是把代码给我？0.0

**Comment by daimajia** [comment]
只有这个版本的，加密的还没有研究过呢
2014-1-23 上午12:14于 "arition" notifications@github.com写道：

**Comment by arition** [comment]
orz其实加密很简单的

首先访问一下地址，如果加密会跳转到http://pan.baidu.com/share/init?shareid=XXXX&uk=XXXX 这样的
这样shareid和uk就有了
还有一个参数是t，就是从1970-1-1到现在的毫秒数

然后访问http://pan.baidu.com/share/verify?shareid=XXXX&uk=XXXX&t=XXXX
post的参数一个是pwd，就是密码；还有一个vcode，默认空的

成功的话返回一个cookie，用那个cookie就可以正常访问下载页了

如果有空的话希望可以更新TATTTTT

**Comment by daimajia** [comment]
没问题，一有空我就更新下~

-- 
代码家   博客  |  微博  |  GitHub  |  G+  |  Twitter
发件人: arition arition
回复: daimajia/bleed-baidu-white reply@reply.github.com
日期: 2014年1月23日 at 上午10:03:49
到: daimajia/bleed-baidu-white bleed-baidu-white@noreply.github.com
邮件标题:  Re: [bleed-baidu-white] 是否能再次开源0.0 (#6)  
orz其实加密很简单的

首先访问一下地址，如果加密会跳转到http://pan.baidu.com/share/init?shareid=XXXX&uk=XXXX 这样的
这样shareid和uk就有了
还有一个参数是t，就是从1970-1-1到现在的毫秒数

然后访问http://pan.baidu.com/share/verify?shareid=XXXX&uk=XXXX&t=XXXX
post的参数一个是pwd，就是密码；还有一个vcode，默认空的

成功的话返回一个cookie，用那个cookie就可以正常访问下载页了

如果有空的话希望可以更新TATTTTT

**Comment by arition** [comment]
如果可以把现在这个版本代码给我就更好了TATT

**Comment by daimajia** [comment]
应该已经发到你邮箱啦~

**Comment by arition** [comment]
抱歉没有收到……可以看一下你的gmail么，我把别的邮箱地址发给你了
一直麻烦你太抱歉了……

**Comment by daimajia** [comment]
你好，又发了一份给你，你检查下gmail邮箱。

-- 
代码家   博客  |  微博  |  GitHub  |  G+  |  Twitter
发件人: arition arition
回复: daimajia/bleed-baidu-white reply@reply.github.com
日期: 2014年1月23日 at 上午10:42:56
到: daimajia/bleed-baidu-white bleed-baidu-white@noreply.github.com
邮件标题:  Re: [bleed-baidu-white] 是否能再次开源0.0 (#6)  
抱歉没有收到……可以看一下你的gmail么，我把别的邮箱地址发给你了
一直麻烦你太抱歉了……

**Comment by gonjay** [comment]
嘿，你也许可以试试七牛云，http://www.qiniu.com/pricing 还有http://www.appfog.com也是不错的选择（国内略慢）

**Comment by daimajia** [comment]
@gonjay 跟云存储有什么关系呢？

**Comment by gonjay** [comment]
跟云存储没关系，和价钱还有方便有关系
2014年2月6日 上午10:39于 "代码家" notifications@github.com写道：

**Comment by daimajia** [comment]
@gonjay 噢噢噢噢~ 七牛 又拍云 avoscloud parse这些早都用上了，不过是在别的项目上。

**Comment by gonjay** [comment]
哦哦，哈哈，你最近在捣腾什么好玩的啊
2014年2月6日 上午10:48于 "代码家" notifications@github.com写道：

**Comment by daimajia** [comment]
@gonjay 倒腾这个呢：https://github.com/daimajia/AnimeTaste

**Comment by gonjay** [comment]
很赞呢，我最近在做rubychina的安卓开源项目
2014年2月6日 上午11:20于 "代码家" notifications@github.com写道：

**Comment by daimajia** [comment]
rubychina的客户端？

-- 
代码家   博客  |  微博  |  GitHub  |  G+  |  Twitter
发件人: GonJay GonJay
回复: daimajia/bleed-baidu-white reply@reply.github.com
日期: 2014年2月6日 at 下午12:01:20
到: daimajia/bleed-baidu-white bleed-baidu-white@noreply.github.com
邮件标题:  Re: [bleed-baidu-white] 是否能再次开源0.0 (#6)  
很赞呢，我最近在做rubychina的安卓开源项目
2014年2月6日 上午11:20于 "代码家" notifications@github.com写道：

**Comment by gonjay** [comment]
对啊，地址在这里呢https://github.com/gonjay/rubychina4android

 有个预览版的下载在这里http://pan.baidu.com/s/1gdkPcMv

**Comment by daimajia** [comment]
做的很棒啊~

-- 
代码家   博客  |  微博  |  GitHub  |  G+  |  Twitter
发件人: GonJay GonJay
回复: daimajia/bleed-baidu-white reply@reply.github.com
日期: 2014年2月6日 at 下午1:10:29
到: daimajia/bleed-baidu-white bleed-baidu-white@noreply.github.com
邮件标题:  Re: [bleed-baidu-white] 是否能再次开源0.0 (#6)  
对啊，地址在这里呢https://github.com/gonjay/rubychina4android

**Comment by gonjay** [comment]
呵呵，过奖了，和你一比算啥哦。
这个是我用ruby写的一个小站，自动化的抓取脚本，主要用在手机上的。
http://wuliaotu.aws.af.cm/boring_images

我在想是不是有可能，做一个客户端，然后能够把网络上最热门的图片、视频都集合起来。当然，这部分内容主要集中在一些用户自发产生的内容。

在 2014年2月6日 下午7:09，代码家 notifications@github.com写道：

**Comment by daimajia** [comment]
@gonjay 做的蛮有意思的嘿~ 做客户端当然是有肯能的呀！
