### ISSUE TITLE
啊哦。

### ISSUE THREAD

**Issue by yudun1989** [daimajia/bleed-baidu-white#7]
建议在api中添加文件大小。
ps: 没有再开源实在是太可惜了  T_T

**Comment by daimajia** [comment]
啊哦~ 再开源又会很快不能用的... 我很快会加上大小的~

**Comment by daimajia** [comment]
文件大小参数已经添加上
http://daimajia.duapp.com/baidu/?url=http://pan.baidu.com/s/17Wq4K

**Comment by yudun1989** [comment]
:) 赞

**Comment by SunRain** [comment]
请问下,有没有研究过在使用pcs rest api情况下,当使用acces token直接在PCS目录下载文件的时候,能否隐藏相关的token,因为最后得到的文件链接是带有token的,而不是像你这样的不带token的.

**Comment by daimajia** [comment]
这个还真没研究过。
