### ISSUE TITLE
支持哪些URL?

### ISSUE THREAD

**Issue by yudun1989** [daimajia/bleed-baidu-white#8]
http://pan.baidu.com/share/link?shareid=1938327270&uk=2855000475&fid=2233423979
这种目前没有做处理是把

**Comment by daimajia** [comment]
这个目前不太支持呀，不过很快就能支持了。我晚上改一下

**Comment by daimajia** [comment]
现在已经支持这种链接类型啦！

**Comment by daimajia** [comment]
http://daimajia.duapp.com/baidu/?url=http://pan.baidu.com/share/link?shareid=60665&uk=3960800092

http://daimajia.duapp.com/baidu/?url=http://pan.baidu.com/share/link?shareid=1938327270&uk=2855000475&fid=2233423979

**Comment by yudun1989** [comment]
:)
